plugins {
    id 'java-library'
}

subprojects {
    apply plugin: 'java-library'

    java.toolchain.languageVersion = JavaLanguageVersion.of(21) // 1.20.1 dùng Java 17, 1.21 dùng 21. Ta set max là 21.

    repositories {
        mavenCentral()
        maven { url = "https://maven.parchmentmc.org" }
    }
}